name: Simple Workflow
on:
 push:
  branches:
    - 'main'
    - 'dev'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
    # Клонируем репозиторий
    - uses: actions/checkout@v4
    # Устанавливаем Python
    - uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    # Установка зависимостей
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv
        uv sync

    - name: check_code
      run: |
        uv run ruff check && echo -e "\e[32mЛинтер не выявил ошибок\e[0m"

    # Выполнение миграций
    - name: make migrations
      run: |
        uv run python manage.py makemigrations
        uv run python manage.py makemigrations api
        uv run python manage.py migrate

    # Запуск сервера в фоновом режиме "&"
    # until ...; do ...; done - bash цикл
    # Он выполняется, пока команда возвращает ненулевой код (то есть ошибку).
    - name: run server
      run: |
        uv run python manage.py runserver &
        until curl -s http://127.0.0.1:8000/; do sleep 1; done

    # Запуск тестов
    - name: test api
      run: |
        curl -X GET http://127.0.0.1:8000/user/ || echo -e "\033[0;31m Ошибка: /user/ \033[0m"
        curl -X GET http://127.0.0.1:8000/user_role/ || echo -e "\033[0;31m Ошибка: /user/ \033[0m"